name: U-Boot Build

on:
#   schedule:
#     - cron: 0 20 * * 0
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WRT_REPO: https://github.com/wuxiuxiu521/AX1800Pro-Uboot
  WRT_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install git python python2.7 build-essential device-tree-compiler -y

      - name: Clone U-Boot Source
        run: |
          git clone https://github.com/wuxiuxiu521/AX1800Pro-Uboot
          cd uboot-ipq60xx
          git checkout master  # 替换为需要的分支

      - name: Build U-Boot
        run: |
          cd uboot-ipq60xx-build/
          ./build.sh

      - name: Show Build Output
        run: |
          echo "The U-Boot binary will be located at: uboot-ipq60xx-build/u-boot.mbn"
          echo "U-Boot failsafe HTTP server IP: 192.168.1.1"
