#=================================================
# Description: Build UBoot for AX1800Pro
# Lisence: MIT
#=================================================

name: 编译 AX1800Pro-Uboot

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: 检出代码
      uses: actions/checkout@main

    - name: 初始化环境
      run: |
        sudo apt-get update
        sudo apt-get install -y git python build-essential device-tree-compiler
        python --version

    - name: 下载源码并切换到正确分支
      run: |
        git clone https://github.com/wuxiuxiu521/AX1800Pro-Uboot -b main uboot
        cd uboot

    - name: 编译 UBoot
      working-directory: ./uboot
      run: |
        ./build.sh
        echo "构建结束"
        echo "查看当前目录内容"
        ls -al

    - name : 打包固件
      uses: actions/upload-artifact@main
      with:
        name: AX1800Pro-Uboot
        path: u-boot.bin, u-boot.mbn  # 上传生成的两个文件
