#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
#=================================================

name: 编译 AX1800Pro-Uboot

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 工作流完毕
      uses: actions/checkout@main

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install git python build-essential device-tree-compiler
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: 下载源码并切换到正确分支
      run: |
        git clone --depth 1 https://github.com/wuxiuxiu521/AX1800Pro-Uboot -b main uboot
        cd uboot

    - name: 安装 Python 2.7 并切换
      run: |
        sudo apt-get install python2.7 -y
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
        python --version

    - name: 编译 UBoot
      working-directory: ./uboot
      run: |
        ./build.sh
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 检查文件是否存在
      working-directory: ./uboot
      run: |
        if [ -f output/u-boot.mbn ]; then
          echo "文件 u-boot.mbn 已生成"
        else
          echo "未找到 u-boot.mbn 文件"
          ls -al output/
        fi

    - name : 打包固件
      uses: actions/upload-artifact@main
      with:
        name: AX1800Pro-Uboot${{ env.FILE_DATE }}
        path: uboot/output/u-boot.mbn  # 修改为实际生成文件的路径
